// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('d:/GitHub/HopAmApp/Code/NguyenIT/node_modules/react');
var { Component } = React;
var ReactNative = require('d:/GitHub/HopAmApp/Code/NguyenIT/node_modules/react-native');
var { AppRegistry } = ReactNative;
var entryPoint = require('d:/GitHub/HopAmApp/Code/NguyenIT/index.js');
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('AwesomeProject', appParameters);
});